coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 2%
        informational: true
    patch:
      default:
        target: 80%
        threshold: 5%
        informational: true
comment:
  layout: "reach, diff, flags, files"
