name: .NET Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write

jobs:
  dotnet-build:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        dotnet-version: [8.0.x]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v7
      - name: Disable autocrlf
        run: git config core.autocrlf false
      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Fetch submodules
        run: git submodule update --init --recursive
      - name: Restore dependencies
        run: dotnet restore
      - name: Build third-party modules
        run: dotnet build ./src/Mocha.Protocol.Generated
      - name: Build
        run: dotnet build
      - name: Format
        run: dotnet format --verify-no-changes --verbosity diagnostic
      - name: Test
        run: dotnet test -c Release --collect:"XPlat Code Coverage"
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v7
        with:
          use_oidc: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
